-- Generated by `npm run db:seed:sql`. Safe to re-run: INSERT IGNORE only fills gaps.
-- Import the schema first — either drizzle/import-all.sql (schema + data in one
-- file) or each drizzle/000X_*.sql in order.

SET NAMES utf8mb4;

-- Settings: one JSON document per group, mirroring lib/types.ts SiteSettings.
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('identity', '{\"company\":\"CV AMANA PERKASA\",\"shortName\":\"AMANA PERKASA\",\"initials\":\"AP\",\"tagline\":\"Event Service & Creative Production\",\"navCta\":\"Konsultasi Event\",\"copyright\":\"All rights reserved.\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('hero', '{\"title\":\"Mewujudkan Event Berkelas, Terukur, dan Berkesan.\",\"description\":\"Kami membantu merancang dan mengeksekusi kebutuhan event secara profesional—mulai dari konsep, produksi, teknis, hingga pelaksanaan di lapangan.\",\"image\":\"/projects/corporate-conference.png\",\"ctaPrimary\":\"Lihat Project\",\"ctaSecondary\":\"Hubungi Kami\",\"scrollHint\":\"Scroll to explore\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('about', '{\"kicker\":\"Tentang Perusahaan\",\"heading\":\"Partner eksekusi untuk event yang harus berjalan tepat.\",\"body\":\"CV AMANA PERKASA bergerak dalam pelayanan jasa event untuk kebutuhan korporasi, instansi, komunitas, pendidikan, hingga acara sosial. Kami mengutamakan koordinasi yang rapi, visual yang kuat, dan eksekusi yang terarah agar setiap acara berjalan sesuai tujuan.\",\"stats\":[{\"value\":\"360°\",\"label\":\"Event Support\"},{\"value\":\"10\",\"label\":\"Project Concepts\"},{\"value\":\"1\",\"label\":\"Integrated Team\"}]}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('services', '{\"kicker\":\"Layanan Kami\",\"heading\":\"Dari ide hingga event selesai.\",\"description\":\"Layanan dapat dikombinasikan sesuai kebutuhan project, skala acara, lokasi, serta scope pekerjaan.\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('projects', '{\"kicker\":\"Selected Projects\",\"heading\":\"Portfolio event.\",\"description\":\"Ganti judul, deskripsi, kategori, dan foto asli project melalui panel admin.\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('process', '{\"kicker\":\"Cara Kerja\",\"heading\":\"Workflow yang terstruktur.\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('team', '{\"kicker\":\"Management & Team\",\"heading\":\"Satu tim, satu kendali project.\",\"description\":\"Struktur ini dibuat sebagai template. Ganti nama dan jabatan sesuai struktur aktual CV AMANA PERKASA.\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('legalities', '{\"kicker\":\"Legalitas Perusahaan\",\"heading\":\"Perusahaan yang terdaftar dan siap mendukung kerja sama profesional.\",\"description\":\"\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('contact', '{\"kicker\":\"Let\'s Collaborate\",\"heading\":\"Punya event yang ingin diwujudkan?\",\"description\":\"Diskusikan kebutuhan acara, scope pekerjaan, timeline, dan kebutuhan teknis bersama tim CV AMANA PERKASA.\",\"phone\":\"08xx-xxxx-xxxx\",\"email\":\"email@perusahaan.com\",\"address\":\"Alamat perusahaan dapat diganti melalui panel admin.\",\"instagram\":\"@amanaperkasa\",\"whatsapp\":\"\"}');
INSERT IGNORE INTO `settings` (`key`, `value`) VALUES ('seo', '{\"title\":\"CV AMANA PERKASA | Event Service & Creative Production\",\"description\":\"Company profile CV AMANA PERKASA — pelayanan jasa event, produksi kreatif, dan event management.\",\"keywords\":\"\",\"ogImage\":\"\",\"canonical\":\"\"}');

-- Services
INSERT IGNORE INTO `services` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (1, '01', 'Corporate Event', 'Seminar, conference, meeting, gathering, launching, dan kebutuhan event perusahaan.', 1, 1);
INSERT IGNORE INTO `services` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (2, '02', 'Wedding & Social Event', 'Perencanaan, dekorasi, teknis, serta koordinasi acara sosial dan pernikahan.', 2, 1);
INSERT IGNORE INTO `services` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (3, '03', 'Exhibition & Booth', 'Konsep booth, layout pameran, produksi area display, dan dukungan operasional.', 3, 1);
INSERT IGNORE INTO `services` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (4, '04', 'Concert & Entertainment', 'Panggung, lighting, audio, LED, talent handling, dan koordinasi produksi hiburan.', 4, 1);
INSERT IGNORE INTO `services` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (5, '05', 'Ceremony & Gathering', 'Acara seremonial, instansi, wisuda, gathering, serta kegiatan formal lainnya.', 5, 1);
INSERT IGNORE INTO `services` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (6, '06', 'Community & Religious Event', 'Dukungan pelaksanaan kegiatan komunitas dan keagamaan dengan kebutuhan yang fleksibel.', 6, 1);

-- Projects
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (1, 'Corporate Conference', 'Corporate Event', '/projects/corporate-conference.png', 'Konsep ballroom modern dengan stage, LED screen, registration, dan area networking.', '', '', '', '', 1, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (2, 'Wedding Reception', 'Social Event', '/projects/wedding-reception.png', 'Konsep resepsi elegan dengan dekorasi floral, stage, aisle, dan banquet setup.', '', '', '', '', 2, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (3, 'Product Launch', 'Brand Activation', '/projects/product-launch.png', 'Panggung peluncuran produk dengan visual LED, reveal moment, dan area display.', '', '', '', '', 3, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (4, 'Live Concert', 'Entertainment', '/projects/live-concert.png', 'Produksi panggung skala besar dengan lighting, audio, LED, dan crowd management.', '', '', '', '', 4, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (5, 'Exhibition', 'Exhibition', '/projects/exhibition.png', 'Area pameran profesional dengan booth modern, circulation flow, dan display zone.', '', '', '', '', 5, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (6, 'Formal Ceremony', 'Ceremony', '/projects/formal-ceremony.png', 'Acara formal dengan tata panggung, podium, seating, dan pengelolaan teknis.', '', '', '', '', 6, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (7, 'Outdoor Festival', 'Public Event', '/projects/outdoor-festival.png', 'Festival terbuka dengan tenant area, stage, lighting, dan pengaturan alur pengunjung.', '', '', '', '', 7, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (8, 'Gala Dinner', 'Corporate Gathering', '/projects/gala-dinner.png', 'Banquet dan gala dinner dengan atmosfer premium, stage, table setting, dan ambience lighting.', '', '', '', '', 8, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (9, 'Graduation Event', 'Education Event', '/projects/graduation.png', 'Konsep acara kelulusan dengan stage formal, aisle, seating, dan dekorasi institusional.', '', '', '', '', 9, 1);
INSERT IGNORE INTO `projects` (`id`, `title`, `category`, `image`, `description`, `client`, `location`, `year`, `scope`, `position`, `published`) VALUES (10, 'Religious Gathering', 'Community Event', '/projects/religious-event.png', 'Acara keagamaan dengan setting panggung yang rapi, seating terorganisir, dan dukungan teknis.', '', '', '', '', 10, 1);

-- Project gallery

-- Company legalities

-- Team
INSERT IGNORE INTO `team_members` (`id`, `role`, `name`, `description`, `photo`, `position`, `published`) VALUES (1, 'Director', 'Nama Direktur', 'Direction & Client Relations', '', 1, 1);
INSERT IGNORE INTO `team_members` (`id`, `role`, `name`, `description`, `photo`, `position`, `published`) VALUES (2, 'Project Manager', 'Nama Project Manager', 'Planning & Project Control', '', 2, 1);
INSERT IGNORE INTO `team_members` (`id`, `role`, `name`, `description`, `photo`, `position`, `published`) VALUES (3, 'Operations', 'Nama Operations', 'Vendor & Field Coordination', '', 3, 1);
INSERT IGNORE INTO `team_members` (`id`, `role`, `name`, `description`, `photo`, `position`, `published`) VALUES (4, 'Creative & Production', 'Nama Creative Lead', 'Concept, Visual & Production', '', 4, 1);

-- Workflow
INSERT IGNORE INTO `workflow_steps` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (1, '01', 'Brief & Consultation', 'Memahami tujuan, audiens, skala, kebutuhan teknis, dan batasan event.', 1, 1);
INSERT IGNORE INTO `workflow_steps` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (2, '02', 'Concept & Planning', 'Menyusun konsep, timeline, kebutuhan produksi, vendor, dan rencana pelaksanaan.', 2, 1);
INSERT IGNORE INTO `workflow_steps` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (3, '03', 'Production', 'Menyiapkan seluruh kebutuhan visual, teknis, venue, talent, dan operasional.', 3, 1);
INSERT IGNORE INTO `workflow_steps` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (4, '04', 'Execution', 'Koordinasi onsite, rundown control, technical control, dan problem solving.', 4, 1);
INSERT IGNORE INTO `workflow_steps` (`id`, `no`, `title`, `description`, `position`, `published`) VALUES (5, '05', 'Evaluation', 'Serah terima dokumentasi, evaluasi pelaksanaan, serta kebutuhan tindak lanjut.', 5, 1);

-- Admin user: UPSERT, so re-running this file resets the password to
-- whatever ADMIN_USERNAME / ADMIN_PASSWORD were at generation time.
INSERT INTO `admin_users` (`username`, `password_hash`) VALUES ('admin', 'scrypt:12b2b9e513683c9aacea6b96c975944a:9aff52fa300fc3b9fdedee6c40cd8c4d878781cea7dabe6991cebfa5aabbe2a21ef4069da0979fb6915afbf2bbc9d87eb0c801c8a1b8792dcff18ff4272764c3') ON DUPLICATE KEY UPDATE `password_hash` = VALUES(`password_hash`);
