/**
 * Seeds MySQL from data/site.json and creates the first admin user.
 *
 *   npm run db:seed        — apply straight to DATABASE_URL (needs Remote MySQL)
 *   npm run db:seed:sql    — write drizzle/seed-data.sql for phpMyAdmin import
 *
 * Idempotent by construction: every INSERT carries an explicit primary key and
 * uses INSERT IGNORE, so re-running never duplicates rows and never overwrites
 * edits made in the admin panel.
 *
 * The same statement list feeds both modes, so the file you import through
 * phpMyAdmin is byte-for-byte what `db:seed` would have executed.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { escape } from "mysql2";
import { hashPassword } from "../lib/password";
import { makeReimportable, stripDrizzleBreakpoints } from "./sql-utils";
import type { SiteContent } from "../lib/types";

const content = JSON.parse(
  readFileSync(new URL("../data/site.json", import.meta.url), "utf8"),
) as SiteContent;

const IDENTIFIER = /^[a-z_`]+$/;

/** Names here come from this file and the registry below, never from user input. */
function table(name: string) {
  if (!IDENTIFIER.test(name)) throw new Error(`Refusing to build SQL for ${name}`);
  return `\`${name}\``;
}

const value = (input: string | number | boolean | null) =>
  input === null ? "NULL" : typeof input === "boolean" ? (input ? 1 : 0) : escape(input);

function insertIgnore(name: string, columns: string[], rows: Array<Array<string | number | boolean | null>>) {
  const cols = columns.map((column) => `\`${column}\``).join(", ");
  return rows.map((row) => {
    const values = row.map(value).join(", ");
    return `INSERT IGNORE INTO ${table(name)} (${cols}) VALUES (${values});`;
  });
}

const SETTINGS_TABLE = ["key", "value"];
const settingRows = (Object.entries(content.settings) as Array<[string, unknown]>).map(
  ([group, groupValues]) => [group, JSON.stringify(groupValues)] as [string, string],
);

const statements = [
  "-- Generated by `npm run db:seed:sql`. Safe to re-run: INSERT IGNORE only fills gaps.",
  "-- Import the schema first — either drizzle/import-all.sql (schema + data in one",
  "-- file) or each drizzle/000X_*.sql in order.",
  "",
  // Content carries em dashes and degree signs. If the database was created with a
  // latin1 default this would store mojibake, so pin the import connection.
  // Drizzle cannot emit a table CHARSET clause, hence doing it here.
  "SET NAMES utf8mb4;",
  "",
  "-- Settings: one JSON document per group, mirroring lib/types.ts SiteSettings.",
  ...insertIgnore("settings", SETTINGS_TABLE, settingRows),
  "",
  "-- Services",
  ...insertIgnore(
    "services",
    ["id", "no", "title", "description", "position", "published"],
    content.services.map((row, index) => [
      row.id,
      row.no,
      row.title,
      row.description,
      index + 1,
      true,
    ]),
  ),
  "",
  "-- Projects",
  ...insertIgnore(
    "projects",
    ["id", "title", "category", "image", "description", "client", "location", "year", "scope", "position", "published"],
    content.projects.map((row, index) => [
      row.id,
      row.title,
      row.category,
      row.image,
      row.description,
      row.client ?? "",
      row.location ?? "",
      row.year ?? "",
      row.scope ?? "",
      index + 1,
      true,
    ]),
  ),
  "",
  // Both default to empty in data/site.json. Emitting them anyway means a fresh
  // install and the SQL import path stay identical if an operator ever adds
  // starter rows, instead of silently dropping them.
  "-- Project gallery",
  ...insertIgnore(
    "project_images",
    ["id", "project_id", "image", "caption", "position"],
    content.projects.flatMap((project) =>
      (project.gallery ?? []).map((image, index) => [
        image.id,
        project.id,
        image.image,
        image.caption ?? "",
        index + 1,
      ]),
    ),
  ),
  "",
  "-- Company legalities",
  ...insertIgnore(
    "company_legalities",
    ["id", "title", "value", "description", "position", "published"],
    content.legalities.map((row, index) => [
      row.id,
      row.title,
      row.value,
      row.description,
      index + 1,
      true,
    ]),
  ),
  "",
  "-- Team",
  ...insertIgnore(
    "team_members",
    ["id", "role", "name", "description", "photo", "position", "published"],
    content.team.map((row, index) => [
      row.id,
      row.role,
      row.name,
      row.description,
      row.photo ?? "",
      index + 1,
      true,
    ]),
  ),
  "",
  "-- Workflow",
  ...insertIgnore(
    "workflow_steps",
    ["id", "no", "title", "description", "position", "published"],
    content.workflow.map((row, index) => [
      row.id,
      row.no,
      row.title,
      row.description,
      index + 1,
      true,
    ]),
  ),
];

async function adminStatement(): Promise<string | null> {
  const username = (process.env.ADMIN_USERNAME || "admin").trim();
  const password = process.env.ADMIN_PASSWORD ?? "";

  if (password.length < 8) {
    console.warn(
      "\n!! ADMIN_PASSWORD kosong atau pendek (< 8 karakter). Baris admin dilewati.\n" +
        "   Set ADMIN_PASSWORD lalu jalankan ulang untuk membuat user pertama.",
    );
    return null;
  }

  const hash = await hashPassword(password);

  // Unlike content rows, the admin password is deliberately UPSERTed: the value
  // in .env at generation time is the single source of truth, so re-running seed
  // also acts as a password reset. With INSERT IGNORE a regenerated .env would
  // silently leave the old hash in place and lock you out of /admin with no error.
  return (
    `INSERT INTO ${table("admin_users")} (\`username\`, \`password_hash\`) VALUES (${value(username)}, ${value(hash)}) ` +
    `ON DUPLICATE KEY UPDATE \`password_hash\` = VALUES(\`password_hash\`);`
  );
}

async function main() {
  const emitSql = process.argv.includes("--emit-sql");
  const admin = await adminStatement();
  const all = admin
    ? [
        ...statements,
        "",
        "-- Admin user: UPSERT, so re-running this file resets the password to",
        "-- whatever ADMIN_USERNAME / ADMIN_PASSWORD were at generation time.",
        admin,
      ]
    : statements;

  if (emitSql) {
    const dataFile = new URL("../drizzle/seed-data.sql", import.meta.url);
    const dataSql = `${all.join("\n")}\n`;
    writeFileSync(dataFile, dataSql, "utf8");

    // One file an operator can import in a single pass: schema with the
    // drizzle-kit breakpoint markers removed, then the seed data.
    const dir = new URL("../drizzle/", import.meta.url);
    const schemaFiles = readdirSync(dir)
      .filter((name) => name.endsWith(".sql") && name !== "import-all.sql" && name !== "seed-data.sql")
      .sort();

    const schemaSql = schemaFiles
      .map((name) => `-- ${name}\n${makeReimportable(stripDrizzleBreakpoints(readFileSync(new URL(name, dir), "utf8")))}`)
      .join("\n\n");

    const combined = [
      "-- CV Amana Perkasa — skema + konten, siap import ke phpMyAdmin.",
      "-- Dihasilkan oleh `npm run db:seed:sql`. Jangan diedit manual; edit data/site.json lalu jalankan ulang.",
      "-- PERINGATAN: file ini memuat hash password admin dari ADMIN_PASSWORD saat dibuat.",
      "--   Impor ulang = reset password admin ke nilai itu. Hapus baris admin_users",
      "--   di bagian bawah file ini bila Anda tidak menginginkannya.",
      "",
      "SET NAMES utf8mb4;",
      "",
      schemaSql,
      "",
      dataSql.trim(),
      "",
    ].join("\n");

    writeFileSync(new URL("../drizzle/import-all.sql", dir), combined, "utf8");

    const count = all.filter((s) => s.endsWith(";")).length;
    console.log(`\nWrote ${count} seed statements -> drizzle/seed-data.sql`);
    console.log(`Wrote combined import         -> drizzle/import-all.sql`);
    console.log("Import drizzle/import-all.sql lewat phpMyAdmin (satu kali jalan, aman diulang).");
    return;
  }

  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("\nDATABASE_URL tidak diset. Pakai `npm run db:seed:sql` untuk membuat file SQL saja.");
    process.exit(1);
  }

  const mysql = await import("mysql2/promise");
  const connection = await mysql.createConnection(url);
  try {
    let applied = 0;
    let skipped = 0;
    for (const statement of all) {
      if (!statement.endsWith(";")) continue;
      try {
        await connection.query(statement);
        applied += 1;
      } catch (error) {
        skipped += 1;
        console.warn(`  dilewati: ${(error as Error).message.slice(0, 120)}`);
      }
    }
    console.log(`\nSeed selesai. ${applied} statement diterapkan, ${skipped} dilewati.`);
    if (admin) console.log(`Admin '${(process.env.ADMIN_USERNAME || "admin").trim()}' siap (bila belum ada).`);
  } finally {
    await connection.end();
  }
}

main().catch((error) => {
  console.error("\nSeed gagal:", (error as Error).message);
  process.exit(1);
});
